apiVersion: v1
kind: Service
metadata:
  name: sip-calculator-service
  labels:
    app: sip-calculator
spec:
  type: NodePort          # Use LoadBalancer if running on cloud (EKS, GKE, AKS)
  selector:
    app: sip-calculator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080      # Access via <NodeIP>:30080
